package net.homecredit.homerselect.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-08-03T17:31:31.528+07:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", name = "CardManagementWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CardManagementWS {

    @WebMethod(operationName = "ConfirmPersonalizedCard")
    @WebResult(name = "ConfirmPersonalizedCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "ConfirmPersonalizedCardResponse")
    public ConfirmPersonalizedCardResponse confirmPersonalizedCard(
        @WebParam(partName = "ConfirmPersonalizedCardRequest", name = "ConfirmPersonalizedCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        ConfirmPersonalizedCardRequest confirmPersonalizedCardRequest
    );

    @WebMethod(operationName = "UnblockCardsByAccountNumber")
    @WebResult(name = "UnblockCardsByAccountNumberResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "UnblockCardsByAccountNumberResponse")
    public UnblockCardsByAccountNumberResponse unblockCardsByAccountNumber(
        @WebParam(partName = "UnblockCardsByAccountNumberRequest", name = "UnblockCardsByAccountNumberRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        UnblockCardsByAccountNumberRequest unblockCardsByAccountNumberRequest
    );

    @WebMethod(operationName = "StolenCard")
    @WebResult(name = "StolenCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "StolenCardResponse")
    public StolenCardResponse stolenCard(
        @WebParam(partName = "StolenCardRequest", name = "StolenCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        StolenCardRequest stolenCardRequest
    );

    @WebMethod(operationName = "ReserveCard")
    @WebResult(name = "ReserveCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "ReserveCardResponse")
    public ReserveCardResponse reserveCard(
        @WebParam(partName = "ReserveCardRequest", name = "ReserveCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        ReserveCardRequest reserveCardRequest
    );

    @WebMethod(operationName = "BlockCardsByAccountNumber")
    @WebResult(name = "BlockCardsByAccountNumberResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "BlockCardsByAccountNumberResponse")
    public BlockCardsByAccountNumberResponse blockCardsByAccountNumber(
        @WebParam(partName = "BlockCardsByAccountNumberRequest", name = "BlockCardsByAccountNumberRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        BlockCardsByAccountNumberRequest blockCardsByAccountNumberRequest
    );

    @WebMethod(operationName = "GetAllowedCardOperationsForUser")
    @WebResult(name = "GetAllowedCardOperationsForUserResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "GetAllowedCardOperationsForUserResponse")
    public GetAllowedCardOperationsForUserResponse getAllowedCardOperationsForUser(
        @WebParam(partName = "GetAllowedCardOperationsForUserRequest", name = "GetAllowedCardOperationsForUserRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        GetAllowedCardOperationsForUserRequest getAllowedCardOperationsForUserRequest
    );

    @WebMethod(operationName = "VerifyEmbossedName")
    @WebResult(name = "VerifyEmbossedNameResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "VerifyEmbossedNameResponse")
    public VerifyEmbossedNameResponse verifyEmbossedName(
        @WebParam(partName = "VerifyEmbossedNameRequest", name = "VerifyEmbossedNameRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        VerifyEmbossedNameRequest verifyEmbossedNameRequest
    );

    @WebMethod(operationName = "ConfirmInstantCard")
    @WebResult(name = "ConfirmInstantCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "ConfirmInstantCardResponse")
    public ConfirmInstantCardResponse confirmInstantCard(
        @WebParam(partName = "ConfirmInstantCardRequest", name = "ConfirmInstantCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        ConfirmInstantCardRequest confirmInstantCardRequest
    );

    @WebMethod(operationName = "BlockCard")
    @WebResult(name = "BlockCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "BlockCardResponse")
    public BlockCardResponse blockCard(
        @WebParam(partName = "BlockCardRequest", name = "BlockCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        BlockCardRequest blockCardRequest
    );

    @WebMethod(operationName = "CreatePersonalizedCard")
    @WebResult(name = "CreatePersonalizedCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "CreatePersonalizedCardResponse")
    public CreatePersonalizedCardResponse createPersonalizedCard(
        @WebParam(partName = "CreatePersonalizedCardRequest", name = "CreatePersonalizedCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        CreatePersonalizedCardRequest createPersonalizedCardRequest
    );

    @WebMethod(operationName = "CreateEmbossedName")
    @WebResult(name = "CreateEmbossedNameResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "CreateEmbossedNameResponse")
    public CreateEmbossedNameResponse createEmbossedName(
        @WebParam(partName = "CreateEmbossedNameRequest", name = "CreateEmbossedNameRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        CreateEmbossedNameRequest createEmbossedNameRequest
    );

    @WebMethod(operationName = "ActivateCard")
    @WebResult(name = "ActivateCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "ActivateCardResponse")
    public ActivateCardResponse activateCard(
        @WebParam(partName = "ActivateCardRequest", name = "ActivateCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        ActivateCardRequest activateCardRequest
    );

    @WebMethod(operationName = "GetPlasticsOfCard")
    @WebResult(name = "GetPlasticsOfCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "GetPlasticsOfCardResponse")
    public GetPlasticsOfCardResponse getPlasticsOfCard(
        @WebParam(partName = "GetPlasticsOfCardRequest", name = "GetPlasticsOfCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        GetPlasticsOfCardRequest getPlasticsOfCardRequest
    );

    @WebMethod(operationName = "HoldBackCard")
    @WebResult(name = "HoldBackCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "HoldBackCardResponse")
    public HoldBackCardResponse holdBackCard(
        @WebParam(partName = "HoldBackCardRequest", name = "HoldBackCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        HoldBackCardRequest holdBackCardRequest
    );

    @WebMethod(operationName = "AddOperatorNote")
    @WebResult(name = "AddOperatorNoteResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "AddOperatorNoteResponse")
    public AddOperatorNoteResponse addOperatorNote(
        @WebParam(partName = "AddOperatorNoteRequest", name = "AddOperatorNoteRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        AddOperatorNoteRequest addOperatorNoteRequest
    );

    @WebMethod(operationName = "ReplaceCard")
    @WebResult(name = "ReplaceCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "ReplaceCardResponse")
    public ReplaceCardResponse replaceCard(
        @WebParam(partName = "ReplaceCardRequest", name = "ReplaceCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        ReplaceCardRequest replaceCardRequest
    );

    @WebMethod(operationName = "NotifyPinChange")
    @WebResult(name = "NotifyPinChangeResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "NotifyPinChangeResponse")
    public NotifyPinChangeResponse notifyPinChange(
        @WebParam(partName = "NotifyPinChangeRequest", name = "NotifyPinChangeRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        NotifyPinChangeRequest notifyPinChangeRequest
    );

    @WebMethod(operationName = "UpdateEmbossedName")
    @WebResult(name = "UpdateEmbossedNameResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "UpdateEmbossedNameResponse")
    public UpdateEmbossedNameResponse updateEmbossedName(
        @WebParam(partName = "UpdateEmbossedNameRequest", name = "UpdateEmbossedNameRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        UpdateEmbossedNameRequest updateEmbossedNameRequest
    );

    @WebMethod(operationName = "CancelCardsByAccountNumber")
    @WebResult(name = "CancelCardsByAccountNumberResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "CancelCardsByAccountNumberResponse")
    public CancelCardsByAccountNumberResponse cancelCardsByAccountNumber(
        @WebParam(partName = "CancelCardsByAccountNumberRequest", name = "CancelCardsByAccountNumberRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        CancelCardsByAccountNumberRequest cancelCardsByAccountNumberRequest
    );

    @WebMethod(operationName = "LostCard")
    @WebResult(name = "LostCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "LostCardResponse")
    public LostCardResponse lostCard(
        @WebParam(partName = "LostCardRequest", name = "LostCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        LostCardRequest lostCardRequest
    );

    @WebMethod(operationName = "FindCard")
    @WebResult(name = "FindCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "FindCardResponse")
    public FindCardResponse findCard(
        @WebParam(partName = "FindCardRequest", name = "FindCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        FindCardRequest findCardRequest
    );

    @WebMethod(operationName = "UnblockCard")
    @WebResult(name = "UnblockCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "UnblockCardResponse")
    public UnblockCardResponse unblockCard(
        @WebParam(partName = "UnblockCardRequest", name = "UnblockCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        UnblockCardRequest unblockCardRequest
    );

    @WebMethod(operationName = "SetCardLimits")
    @WebResult(name = "SetCardLimitsResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "SetCardLimitsResponse")
    public SetCardLimitsResponse setCardLimits(
        @WebParam(partName = "SetCardLimitsRequest", name = "SetCardLimitsRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        SetCardLimitsRequest setCardLimitsRequest
    );

    @WebMethod(operationName = "GetCard")
    @WebResult(name = "GetCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "GetCardResponse")
    public GetCardResponse getCard(
        @WebParam(partName = "GetCardRequest", name = "GetCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        GetCardRequest getCardRequest
    );

    @WebMethod(operationName = "CancelCard")
    @WebResult(name = "CancelCardResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "CancelCardResponse")
    public CancelCardResponse cancelCard(
        @WebParam(partName = "CancelCardRequest", name = "CancelCardRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        CancelCardRequest cancelCardRequest
    );

    @WebMethod(operationName = "GetCards")
    @WebResult(name = "GetCardsResponse", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2", partName = "GetCardsResponse")
    public GetCardsResponse getCards(
        @WebParam(partName = "GetCardsRequest", name = "GetCardsRequest", targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2")
        GetCardsRequest getCardsRequest
    );
}
