package net.homecredit.homerselect.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 2.5.1
 * 2018-08-03T17:31:31.597+07:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "CardManagementWSSoap11QSService", 
                  wsdlLocation = "file:/D:/Documents/Java/SampleImportWS/src/main/resources/wsdl/CardManagementService_v2.wsdl",
                  targetNamespace = "http://homecredit.net/homerselect/ws/card/management/v2") 
public class CardManagementWSSoap11QSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://homecredit.net/homerselect/ws/card/management/v2", "CardManagementWSSoap11QSService");
    public final static QName CardManagementWSSoap11QSPort = new QName("http://homecredit.net/homerselect/ws/card/management/v2", "CardManagementWSSoap11QSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Documents/Java/SampleImportWS/src/main/resources/wsdl/CardManagementService_v2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CardManagementWSSoap11QSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/Documents/Java/SampleImportWS/src/main/resources/wsdl/CardManagementService_v2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CardManagementWSSoap11QSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CardManagementWSSoap11QSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardManagementWSSoap11QSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardManagementWSSoap11QSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardManagementWSSoap11QSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CardManagementWSSoap11QSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CardManagementWS
     */
    @WebEndpoint(name = "CardManagementWSSoap11QSPort")
    public CardManagementWS getCardManagementWSSoap11QSPort() {
        return super.getPort(CardManagementWSSoap11QSPort, CardManagementWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardManagementWS
     */
    @WebEndpoint(name = "CardManagementWSSoap11QSPort")
    public CardManagementWS getCardManagementWSSoap11QSPort(WebServiceFeature... features) {
        return super.getPort(CardManagementWSSoap11QSPort, CardManagementWS.class, features);
    }

}
