
package net.homecredit.homerselect.ws;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Creates personalized card instance. Card number is generated by CMS from sequence associated to the
 *                     CardType.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="holderCuid" type="{http://homecredit.net/homerselect/ws/card/common/v2}Cuid"/>
 *         &lt;element name="account" type="{http://homecredit.net/homerselect/ws/card/common/v2}AccountDto"/>
 *         &lt;element name="cardTypeId" type="{http://homecredit.net/homerselect/ws/card/common/v2}CardType"/>
 *         &lt;element name="serviceCode" type="{http://homecredit.net/homerselect/ws/card/common/v2}ServiceCode"/>
 *         &lt;element name="approvedCreditLimit" type="{http://homecredit.net/homerselect/ws/card/common/v2}ApprovedCreditLimit"/>
 *         &lt;element name="posDeliveryAddress" type="{http://homecredit.net/homerselect/ws/card/common/v2}PosDeliveryAddressDto"/>
 *         &lt;element name="embossedName" type="{http://homecredit.net/homerselect/ws/card/common/v2}HolderName" minOccurs="0"/>
 *         &lt;element name="cardHolderName" type="{http://homecredit.net/homerselect/ws/card/management/v2}CardHolderName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "holderCuid",
    "account",
    "cardTypeId",
    "serviceCode",
    "approvedCreditLimit",
    "posDeliveryAddress",
    "embossedName",
    "cardHolderName"
})
@XmlRootElement(name = "CreatePersonalizedCardRequest")
public class CreatePersonalizedCardRequest {

    protected long holderCuid;
    @XmlElement(required = true)
    protected AccountDto account;
    @XmlElement(required = true)
    protected String cardTypeId;
    @XmlElement(required = true)
    protected String serviceCode;
    @XmlElement(required = true)
    protected BigDecimal approvedCreditLimit;
    @XmlElement(required = true)
    protected PosDeliveryAddressDto posDeliveryAddress;
    protected String embossedName;
    protected CardHolderName cardHolderName;

    /**
     * Gets the value of the holderCuid property.
     * 
     */
    public long getHolderCuid() {
        return holderCuid;
    }

    /**
     * Sets the value of the holderCuid property.
     * 
     */
    public void setHolderCuid(long value) {
        this.holderCuid = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDto }
     *     
     */
    public AccountDto getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDto }
     *     
     */
    public void setAccount(AccountDto value) {
        this.account = value;
    }

    /**
     * Gets the value of the cardTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardTypeId() {
        return cardTypeId;
    }

    /**
     * Sets the value of the cardTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardTypeId(String value) {
        this.cardTypeId = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceCode(String value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the approvedCreditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getApprovedCreditLimit() {
        return approvedCreditLimit;
    }

    /**
     * Sets the value of the approvedCreditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setApprovedCreditLimit(BigDecimal value) {
        this.approvedCreditLimit = value;
    }

    /**
     * Gets the value of the posDeliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PosDeliveryAddressDto }
     *     
     */
    public PosDeliveryAddressDto getPosDeliveryAddress() {
        return posDeliveryAddress;
    }

    /**
     * Sets the value of the posDeliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PosDeliveryAddressDto }
     *     
     */
    public void setPosDeliveryAddress(PosDeliveryAddressDto value) {
        this.posDeliveryAddress = value;
    }

    /**
     * Gets the value of the embossedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmbossedName() {
        return embossedName;
    }

    /**
     * Sets the value of the embossedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmbossedName(String value) {
        this.embossedName = value;
    }

    /**
     * Gets the value of the cardHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link CardHolderName }
     *     
     */
    public CardHolderName getCardHolderName() {
        return cardHolderName;
    }

    /**
     * Sets the value of the cardHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardHolderName }
     *     
     */
    public void setCardHolderName(CardHolderName value) {
        this.cardHolderName = value;
    }

}
